# Generated by Django 4.2.5 on 2024-11-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['first_player'], name='games_match_first_p_6275e1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['second_player'], name='games_match_second__b7475e_idx'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['match'], name='games_round_match_i_ce4a46_idx'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['tournament'], name='games_round_tournam_175f67_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['created_at'], name='games_tourn_created_c327b4_idx'),
        ),
    ]
