# Generated by Django 4.2.5 on 2024-12-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_active_session_id_user_last_activity'),
        ('games', '0002_match_games_match_first_p_6275e1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_scored', models.IntegerField(default=0)),
                ('serves', models.IntegerField(default=0)),
                ('successful_serves', models.IntegerField(default=0)),
                ('total_hits', models.IntegerField(default=0)),
                ('longest_rally', models.IntegerField(default=0)),
                ('overtime_points', models.IntegerField(default=0)),
                ('total_duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_duration',
        ),
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to='users.user'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='tournament_alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='matchhistory',
            index=models.Index(fields=['user'], name='games_match_user_id_d19670_idx'),
        ),
        migrations.AddIndex(
            model_name='matchhistory',
            index=models.Index(fields=['match'], name='games_match_match_i_f99807_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament'], name='games_tourn_tournam_eaf1ba_idx'),
        ),
        migrations.AddField(
            model_name='matchplayerstats',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='games.match'),
        ),
        migrations.AddField(
            model_name='matchplayerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddIndex(
            model_name='matchplayerstats',
            index=models.Index(fields=['match', 'player'], name='games_match_match_i_56a186_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchplayerstats',
            unique_together={('match', 'player')},
        ),
    ]
