# Generated by Django 4.2.5 on 2024-11-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['user'], name='users_frien_user_id_dc4b91_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['friend'], name='users_frien_friend__2d6560_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['user'], name='users_users_user_id_531add_idx'),
        ),
    ]
