# Generated by Django 4.2.5 on 2024-12-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
