# Generated by Django 4.2.5 on 2024-12-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_active_session_id_user_last_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
